@baseUrl = http://localhost:3000

@invalidToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
@validTokenExists1 = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRldi5taW5kZG9jLmNvbSJ9.eyJjb21tdW5pdHkiOiJhbHBoYSIsImZpYXQiOjE2MDAwODU2NDksImdyb3VwIjoicGF0aWVudCIsImxlZ2FsVGVybXMiOnsiZ21iaCI6ZmFsc2UsIm12eiI6ZmFsc2V9LCJwbGF0Zm9ybSI6IndlYiIsInJvbGVzIjpbImNvbnRlbnQuY2xpZW50IiwidGhlcmFweVNlc3Npb24uY2xpZW50IiwidmlkZW9DaGF0LmNsaWVudCJdLCJ1dWlkIjoiZWNmMGZiMzgtMWZlOS0xMWU4LWEyOTYtMDI0MmFjMTEwMDAyIiwiaWF0IjoxNjAwMDg1NjQ5LCJleHAiOjE2MDAxNzIwNDksImlzcyI6ImRldmVsb3BtZW50QG1pbmRkb2MuY29tIiwianRpIjoiNjM1NDc3MTgtNjNlNy00M2NiLTgxNDMtZWM4MGM4ZTY4ZGY3In0.D64sbetHMgxHGoBlY6UlZI4D9ffI-NvhVisvCfB7Pxqu9gjQ6Tw1e2ACMnDET6RGMAyhfha74g02wHUKQIYF-cddeCLWLP4ynirc-MNKykRaM423gy3WnDOZuUG4LB9bMajGqgYPYo_ub8AE3dvAvLsUm9jDwXz1akb-rz922Ge-9Whs7zp4h3YJhYZ4_auDo8JeoOrbJcxQ1D9iX9bN-Q3vUQF_hsd4KRc-th8gwC-I43ZdMuxWwRKSB315VPSNm8ueFqjNL1YQoobcI7wTWXDOFvEHT_XEgKocSjEpyv6ou1Tq4cn3b8FQsS9jwfYmnPcyt1u0udnpMXU9lya-0A
@validTokenExists2 = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21tdW5pdHkiOiJhbHBoYSIsImZpYXQiOjE2MDAwODU2NDksImdyb3VwIjoicGF0aWVudCIsImxlZ2FsVGVybXMiOnsiZ21iaCI6ZmFsc2UsIm12eiI6ZmFsc2V9LCJwbGF0Zm9ybSI6IndlYiIsInJvbGVzIjpbImNvbnRlbnQuY2xpZW50IiwidGhlcmFweVNlc3Npb24uY2xpZW50IiwidmlkZW9DaGF0LmNsaWVudCJdLCJ1dWlkIjoiZGRiMWE4YWYtOTBkMi00NWJlLTk0NTktZGE0MTA2MDY1NTNlIiwiaWF0IjoxNjAwMDg1NjQ5LCJleHAiOjE2MDAxNzIwNDksImlzcyI6ImRldmVsb3BtZW50QG1pbmRkb2MuY29tIiwianRpIjoiNDJkMTRjODItNzM5Yi00YzYwLWJkYWEtOTRiYTViN2RlMDBhIn0.nAG7-nIbgTxWxb1eFczenJpX9zv0WkWBns397jur4nD1T-76yuLkZDWKPJEtdx0_Tf9DfsUOQF8df73ZamXN4_Y4eqUKpxoCmBSoFsx3mEXQkr6waWt0AvQvMxOyKBhFNaAgYp9QghoCduz1JWqw5D1SLBsKwz0JzXIui9_E26rsyrnk35TiRiGVUalJqRj-avDzW4Aq8IcwoyfuQ_8sucTSuNzj3XhqFQJkENK0CVeTJfW1WJQkubGaiOGkw7v8QSvW8bQytU8SHqdhwwl4DFkkw-tu76oEQPyw3axQ_LVC57jPfF3sgTPwCsaNpfYPKi2CSi13gaJc4_CfRoq-Ew
@validTokenNotExists = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21tdW5pdHkiOiJhbHBoYSIsImZpYXQiOjE2MDAwODU2NDksImdyb3VwIjoicGF0aWVudCIsImxlZ2FsVGVybXMiOnsiZ21iaCI6ZmFsc2UsIm12eiI6ZmFsc2V9LCJwbGF0Zm9ybSI6IndlYiIsInJvbGVzIjpbImNvbnRlbnQuY2xpZW50IiwidGhlcmFweVNlc3Npb24uY2xpZW50IiwidmlkZW9DaGF0LmNsaWVudCJdLCJ1dWlkIjoiYWNmMGZiMzgtMWZlOS0xMWU4LWEyOTYtMDI0MmFjMTEwMDAyIiwiaWF0IjoxNjAwMDg1NjQ5LCJleHAiOjE2MDAxNzIwNDksImlzcyI6ImRldmVsb3BtZW50QG1pbmRkb2MuY29tIiwianRpIjoiNjM1NDc3MTgtNjNlNy00M2NiLTgxNDMtZWM4MGM4ZTY4ZGY3In0.gSG2eroqY5PPo85oEmYS-4u6aB4LZBxpkCd1uV6Q-I8wQr4iG6Fkh83Fe7oGCTML46WqfKgF9O_c0Z4TeCJR5DT3FbkxnR22bg4Hsmx8kWj5wYn0ouW44WJHF6G9GY5O-kqSu0Bc3p6QPZhVZo0yReLhjQGPJkPoUwHnN6KEGK7C-Bff-YBdbfXO59IsakPz9zia2QjUiwh3k_8yrmcv45ErSKfNNiIp3pjv_jIc0yyNAUd8vvRyWaQGLKX78dqCaGh3uuTOiVz8Gwob4cQDsUM-deZ9r0Z9WCj3QiAKdElor2SVwsWsU50aSDDFtyAQcV88JCUIOP2quzZJR-mopg

### Invalid JWT
GET {{baseUrl}}/jwt HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{invalidToken}}

### Valid JWT - Exists
GET {{baseUrl}}/jwt HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{validTokenExists1}}

### Valid JWT - Does not exist
GET {{baseUrl}}/jwt HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{validTokenNotExists}}
