version: "3.7"

services:
    redis-db:
        hostname: redis
        image: redis:6-alpine
        container_name: redis-db
        ports:
            - 6379:6379
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"

    speckle:
        image: speckle:1.0
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis-db
        container_name: speckle
        ports:
            - 3000:3000
        environment:
            REDIS_URL: redis://redis-db:6379
